# Generated by Django 4.1.7 on 2023-03-18 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userphotos',
            name='album_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='main.useralbum'),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='caption',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='useralbum',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
