# Generated by Django 4.1.7 on 2023-03-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercategory',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
