# Generated by Django 4.1.7 on 2023-05-26 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_account.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250, verbose_name='first name')),
                ('last_name', models.CharField(max_length=250, verbose_name='last name')),
                ('business_name', models.CharField(max_length=250, verbose_name='business_name')),
                ('role', models.CharField(max_length=250, verbose_name='role')),
                ('client', models.CharField(max_length=250, verbose_name='client')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('password', models.CharField(max_length=300, verbose_name='password')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('is_admin', models.BooleanField(default=False, verbose_name='admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='deleted')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('client_provider', models.CharField(default='self_auth', max_length=200, null=True, verbose_name='client_provider')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('users_can_view_profile', 'Users Can View Profile'), ('users_can_download', 'Users Can Download'), ('users_can_favorite', 'Users Can Favorite'), ('users_can_comment', 'Users Can Comment'), ('users_can_share', 'Users Can Share'), ('can_create_album', 'Can Create Album'), ('can_view_album', 'Can View Album'), ('can_publish_album', 'Can Publish Album'), ('security_alert', 'Security Alert'), ('album_notification', 'Album Notification'), ('download_notification', 'Download Notification'), ('favorites_notification', 'Favorites Notification'), ('comment_notification', 'Comment Notification')],
            },
            managers=[
                ('objects', user_account.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('expiry_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
