# Generated by Django 4.1.7 on 2023-03-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_provider',
            field=models.CharField(default='self_auth', max_length=200, null=True, verbose_name='client_provider'),
        ),
    ]
