# Generated by Django 4.1.7 on 2023-05-18 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_user_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='timestamp',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
