# Generated by Django 4.1.7 on 2023-03-24 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('users_can_view_profile', 'Users Can View Profile'), ('users_can_download', 'Users Can Download'), ('users_can_favorite', 'Users Can Favorite'), ('users_can_comment', 'Users Can Comment'), ('users_can_share', 'Users Can Share'), ('can_create_album', 'Can Create Album'), ('can_view_album', 'Can View Album'), ('can_publish_album', 'Can Publish Album'), ('security_alert', 'Security Alert'), ('album_notification', 'Album Notification'), ('download_notification', 'Download Notification'), ('favorites_notification', 'Favorites Notification'), ('comment_notification', 'Comment Notification')]},
        ),
    ]
