# Generated by Django 4.1.7 on 2023-04-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
