# Generated by Django 4.1.7 on 2023-03-23 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_album', 'Can Create Album'), ('can_view_album', 'Can View Album'), ('can_publish_album', 'Can Publish Album'), ('security_alert', 'Security Alert')]},
        ),
    ]
