# Generated by Django 4.1.7 on 2023-04-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_userotp_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='timestamp',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
